spring.application.name=tripnest-backend

# ==========================================
# DATABASE CONFIGURATION
# ==========================================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tripnest_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:pushpa@123}

# ==========================================
# JPA CONFIGURATION
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================
# FILE UPLOAD CONFIGURATION
# ==========================================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

file.upload-dir=${UPLOAD_DIR:uploads}
server.port=${PORT:8080}