spring.application.name=tripnest-backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/tripnest_db
spring.datasource.username=root
spring.datasource.password=pushpa@123

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
